# Generated by Django 3.0.6 on 2020-05-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
