# Generated by Django 3.0.6 on 2020-05-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0002_auto_20200522_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
